# Generated by Django 3.1.7 on 2021-03-13 05:14

import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=128)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("magazine_subtitle", models.CharField(max_length=128)),
                ("magazine_description", models.TextField()),
                (
                    "magazine_cover",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="books/magazine_cover/",
                        verbose_name="Magazine cover Image",
                    ),
                ),
                (
                    "magazine_mockup",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="books/magazine_mockup/",
                        verbose_name="Magazine Mockup Image",
                    ),
                ),
                ("magazine_file", models.FileField(max_length=128, upload_to="")),
            ],
            options={
                "verbose_name": "About Magazine",
                "verbose_name_plural": "About Magazine",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("subtitle", models.CharField(max_length=128)),
                ("file", models.FileField(max_length=128, upload_to="")),
                (
                    "cover",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="books/covers/", verbose_name="Cover Image"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"verbose_name": "Book", "verbose_name_plural": "Books"},
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("message", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"verbose_name": "Message", "verbose_name_plural": "Messages"},
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                (
                    "photo",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="books/covers/", verbose_name="News Image"
                    ),
                ),
                ("date", models.DateField()),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"verbose_name": "News", "verbose_name_plural": "Newses"},
        ),
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media", models.CharField(max_length=128)),
                ("link", models.URLField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Social Media",
                "verbose_name_plural": "Social Medias",
            },
        ),
        migrations.CreateModel(
            name="Wish",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("designation", models.CharField(max_length=128)),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"verbose_name": "Wish", "verbose_name_plural": "Wishes"},
        ),
    ]
